paths:
  raw_data_dir: data/raw
  interim_data_dir: data/interim
  processed_data_dir: data/processed
  artifacts_dir: artifacts
  reference_data_dir: data/reference
  model_base_dir: data/processed/model_base
  trained_models_dir: artifacts/models
  master_join_table: data/processed/model_base/master_join_table.parquet
  match_splits: config.yaml

pitch:
  length_m: 105.0
  width_m: 68.0

match_splits:
  split_strategy: match_id_holdout_sorted_v1
  train:
    - "678949"
    - "679026"
    - "679053"
    - "679072"
    - "679075"
    - "679088"
    - "679104"
    - "679128"
    - "682607"
    - "682717"
    - "682815"
    - "683132"
    - "683190"
    - "683253"
    - "683261"
    - "683309"
    - "683425"
    - "684014"
    - "684119"
    - "684139"
    - "684141"
    - "684147"
    - "689340"
  validation:
    - "689526"
    - "689552"
    - "689556"
    - "713886"
    - "713893"
  test:
    - "713910"
    - "713946"
    - "713998"
    - "714000"
    - "745399"

etl:
  default_match_id: "679026"
  max_rows: 40

step2:
  all_matches: true
  match_id: "679026"
  event_type_names:
    - PASS
    - BALL TOUCH
    - AERIAL
    - TACKLE
    - BALL RECOVERY
    - FOUL
    - TAKEON
