name: driblabvenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - joblib
  - matplotlib
  - pyarrow
  - pyyaml
  - scikit-learn
  - flake8
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - -e .
